[project]
name = "hyperliquid-examples"
version = "0.1.0"
description = "Hyperliquid spot token sniper bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hyperliquid-python-sdk>=0.17.0",
    "eth-account>=0.10.0",
]
